apiVersion: v1
kind: Service
metadata:
  labels:
    app: myservice
  name: myservice
spec:
  ports:
  - name: helloworldport
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: helloworld
  type: LoadBalancer
status:
  loadBalancer: {}
